# where repo exists
REPOSITORY_HOME =  "${HOME}/.mp/packages/"

#  location of machu-picchu
MP_HOME = "/data/data/com.termux/files/usr/local/machu-picchu/"

# where the packages installed from repositories go
INSTALL_HOME = "/data/data/com.termux/files/usr/local/"

# where the symlink to the installed packages(from repo) exist
BIN_HOME = "/data/data/com.termux/files/usr/bin"

# for dependency management
DEFAULT_PATH           = "./"
DEFAULT_SAVE_DIRECTORY = ".mp/"
